#!/bin/bash

docker build --tag="uphold-ui:dockerfile" --file="Dockerfile.ui" .
docker run \
  -it \
   --entrypoint=/bin/bash \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v `pwd`/dev:/etc/uphold \
  -v `pwd`/dev/logs:/var/log/uphold \
  uphold-ui:dockerfile
