#!/bin/bash

docker build -t "uphold:dockerfile" .
docker run \
  -it \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v `pwd`/config:/opt/uphold/config \
  -v `pwd`/tests:/opt/uphold/tests \
  -v `pwd`/test/blobs:/var/backups/mongo \
  uphold:dockerfile \
  config/local-mongo.yml
