#!/bin/bash

docker build --tag="uphold-tester:dockerfile" --file=Dockerfile.tester .
docker build --tag="uphold-ui:dockerfile" --file=Dockerfile.ui .

docker run \
  -it \
  --rm \
  -p 80:80 \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v `pwd`/dev:/etc/uphold \
  -v `pwd`/dev/logs:/var/log/uphold \
  uphold-ui:dockerfile
