#!/bin/bash

docker build --tag="uphold-ui:dockerfile" --file=Dockerfile.ui .
docker run \
  -it \
  -p 80:80 \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v `pwd`/dev/uphold.yml:/etc/uphold/uphold.yml \
  uphold-ui:dockerfile
