#!/bin/bash

docker build --tag="uphold-tester:dockerfile" --file=Dockerfile.tester .
docker run \
  -it \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v `pwd`/dev/logs:/var/log/uphold \
  -v `pwd`/dev:/etc/uphold \
  uphold-tester:dockerfile \
  s3-mongo.yml

if [ $? -eq 0 ]; then
  echo Success
else
  echo Failed
fi
