#!/bin/bash

docker build --tag="uphold-tester:dockerfile" --file=Dockerfile.tester .
docker run \
  -it \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v `pwd`/dev/uphold.yml:/etc/uphold/uphold.yml \
  -v `pwd`/dev/conf.d:/etc/uphold/conf.d \
  -v `pwd`/dev/tests:/etc/uphold/tests \
  -v `pwd`/dev/blobs:/var/backups \
  -v `pwd`/dev/custom/engines:/etc/uphold/engines \
  -v `pwd`/dev/custom/transports:/etc/uphold/transports \
  uphold-tester:dockerfile \
  development.yml

if [ $? -eq 0 ]; then
  echo Success
else
  echo Failed
fi
