#!/bin/bash

docker build --tag="uphold-tester:dockerfile" --file="Dockerfile.tester" .
docker run \
  -it \
   --entrypoint=/bin/bash \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v `pwd`/dev:/etc/uphold \
  -v `pwd`/dev/logs:/var/log/uphold \
  uphold-tester:dockerfile
