FROM ruby:2.3-slim

RUN apt-get update
RUN apt-get -y install build-essential

WORKDIR /opt/uphold
COPY Gemfile /opt/uphold/Gemfile
COPY Gemfile.lock /opt/uphold/Gemfile.lock
RUN bundle install --without tester development
ADD . /opt/uphold

# remove un-needed directories
RUN rm -rf dev docs

EXPOSE 80
CMD ["bundle", "exec", "rackup", "config.ru", "-p", "80", "-s", "thin", "-o", "0.0.0.0"]
